### PR TITLE
added sorting on finished as other sorts feel redundant

### PR DESCRIPTION
**Pull request by CJMeek**
Signed-off-by: CJMeek <up887397@myport.ac.uk>

After a discussing with Will Yates, it seems that the only useful sort is on finished.

### CODE REVIEW

**Review by Michael-Baylis — CHANGES_REQUESTED** [review]
Disagree.    Sorting needs to be enabled on status, test class and finished.

**Comment by Michael-Baylis** [comment]
Also,  sorting not working properly on the table,     only works on the page,  should we working on the results as a whole.    The sorting is not being relayed to the API server

**Comment by CJMeek** [comment]
> Disagree. Sorting needs to be enabled on status, test class and finished.

I feel like if you can already filter by status and test class why would you need to sort by status and test class, what are the benefits?

**Comment by CJMeek** [comment]
> Also, sorting not working properly on the table, only works on the page, should we working on the results as a whole. The sorting is not being relayed to the API server

This is what this PR aims to fix :)

**Comment by Michael-Baylis** [comment]
because you might want to view all tests for core regression,   then sort on status to see what the failures are in the overall picture then sort by class name.
It is barely any work to enable sorting on this,  so I don't understand why you want to withdraw functionality because it doesn't match the way you prefer to work.

**Comment by Michael-Baylis** [comment]
frankly,  it would look very odd to a customer that you couldn't sort on those fields.

**Comment by Michael-Baylis** [comment]
Also,  you can only filter on single values.      Failed, Failed_with_Defects, envfail, lost, etc.   sorting is at the moment the only way to see all these in one go

**Comment by CJMeek** [comment]
Completely agree hadn't thought about it like that. Just wanted to know why your opinion differed. Very helpful.

**Review by Michael-Baylis — APPROVED** [review]

**Pull request merged**
